feat: Add Velas Blockchain Currency & NPM Package
blooo-io/ledger-live pull request #1
Opened 2022-06-08 10:38 UTC by Z4karia

### 📝 Description

- Added VLX Cryptocurrency
- Added NPM Package for Velas App Integration

### ❓ Context

- **Impacted projects**: `hw-app-velas` 
- **Linked resource(s)**: `https://github.com/LedgerHQ/ledgerjs/pull/827` 

### ✅ Checklist

- [x] **Test coverage** 
- [x] **Atomic delivery** 
- [x] **No breaking changes** 

### 📸 Demo

### 🚀 Expectations to reach

_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps)._

_Pull Requests must pass the CI and be internally validated in order to be merged._

2022-06-08 10:39 UTC, Z4karia commented
The PR is ready @n4l5u0r

2022-06-09 09:06 UTC, n4l5u0r requested changes

2022-06-09 09:06 UTC, n4l5u0r commented on libs/ledgerjs/packages/hw-app-velas/package.json
> +        "url": "https://github.com/LedgerHQ/ledgerjs"
pas le bon repo

2022-06-09 09:06 UTC, n4l5u0r commented on libs/ledgerjs/packages/hw-app-velas/package.json
> +        "url": "https://github.com/LedgerHQ/ledgerjs"
same here

2022-06-09 09:06 UTC, n4l5u0r commented on libs/ledgerjs/packages/hw-app-velas/package.json
> +    "homepage": "https://github.com/LedgerHQ/ledgerjs",
same here

2022-06-09 15:16 UTC, n4l5u0r requested changes

2022-06-09 15:16 UTC, n4l5u0r commented on libs/ledgerjs/packages/hw-app-velas/README.md
> +[Github](https://github.com/LedgerHQ/ledgerjs/),
not correct github repo

2022-06-09 15:41 UTC, n4l5u0r approved these changes

2022-06-09 15:43 UTC, merged